```{r, include=FALSE}

packages <- c(
  "dbscan", "dplyr", "extrafont", "geosphere", "ggplot2", "ggspatial", "grid",
  "jsonlite", "lattice", "leaflet", "leaflet.extras", "leafpop", "magick", "mapdeck",
  "magrittr", "maps", "mapview", "nycflights13", "openrouteservice", "patchwork",
  "raster", "RColorBrewer", "readr", "readxl", "rgdal", "scico", "sf", "spData",
  "tmap", "vapoRwave", "viridis"
)
# check which packages are not installed
not_installed <- packages[!packages %in% installed.packages()[, "Package"]]
# install missing packages
if (length(not_installed) > 1) {
  install.packages(not_installed, repos = "https://cran.rstudio.com/" )
}
if (!"vapoRwave" %in% installed.packages()[, "Package"]) {
  devtools::install_github("moldach/vapoRwave")
}
if (!"openrouteservice" %in% installed.packages()[, "Package"]) {
  devtools::install_github("GIScience/openrouteservice-R")
}
# load the packages
lapply(packages, library, character.only = TRUE)
```

# Introduction
One of the most important aspects of working with geographical data is the presentation and communication of the results. The former should be as creative as possible without losing intuitiveness. Visual effects help to understand trends, discover outliers and uncover patterns. Data visualization is essential for analyzing large amounts of information and making decisions based on data. Trends and outliers can be seen with just a quick glance at a graph. In comparison to a large Excel spreadsheet or similar, visual elements are much more effective in detecting trends. An important part of data analysis is geospatial analysis, i.e. the analysis of geographical data. In order to visualize this data, different packages can be used in **R**.
This book will deal with these packages and how they can be used to represent geospatial data.
  
All of the data used in this book is available in the github repository. (https://github.com/nicoFhahn/geocomputation)
  
Please note that some of the html-plots in this book may take a few seconds to load.
