---
title: "fazit"
author: "Nico Hahn"
date: "27 8 2019"
output: html_document
---

# Fazit
Welches Paket sollte also benutzt werden? Die Pakete haben teilweise in unterschiedlichen Gebieten ihre Stärken.

Für eine Arbeit die beispielsweise in einem Journal beobachtet wird, ist davon auszugehen dass interaktive Karten nicht interaktiv bleiben. Hierfür würden sich **tmap** und **gplot2** mit **ggspatial** hervorragend eignen. Mit ersterem kann mit nur sehr wenig Aufwand eine leicht zu lesende Karte erstellt werden die essentiellen Informationen überliefert. Ist man bereit etwas mehr Aufwand in die Entwicklung einer Karte zu stecken, können mit **ggplot2** äußerst schönen Karten erstellt werden. Normalerweise reicht **tmap** jedoch.

Soll die Grafik in ein HTML-Dokument oder ähnliches eingebunden werden, macht es Sinn die Karte interaktiv zu gestalten. **tmap** bietet hier den Vorteil, dass bei Kenntniss des Pakets mit nur einer Zeile Code jede Karte interaktiv gemacht werden kann. Mit **mapview**, **mapdeck** und **leaflet** können allerdings Karten mit mehr Funktionalität erstellt werden und auch die Syntax ist leicht zu erlenen. Von diesen drei Pakete lassen sich am einfachsten Karten mit **mapview** erstellen. **leaflet** bietet von allen Paketen die größte Individualisierbarkeit an und kann durch das Einbinden von JavaScript Code mit zusätzlicher Funktionalität versetzt werden. Bei großen Datensätzen hingegen ist **mapdeck** geeignet, dass diese sehr schnell visualisieren kann.

Ist das Ziel nur die Exploration eines oder mehrerer Datensätze ist **shiny** eine der besten Möglichkeiten um verschiedenstes Facetten der Daten zu visualisieren. Die Alternative, jedes mal eine neue Grafik erstellen, ist schlicht nicht effizient genug. **leaflet** lässt sich sehr gut mit **shiny** vereinbaren und durch eine Kombination der beiden Pakete können äußerst attraktive Web Apps erstellt werden.