---
title: "Source and Packages"
author: "Nico Hahn"
date: "26 8 2019"
output: html_document
---


# Quellen
Zur Erstellung dieser Arbeit wurden neben den zu Beginn erwähnten Datenquellen nur die Hilfeseiten der zur Visualisierung benutzten Pakete verwendet. Dazu zählen:

  * tmap: https://geocompr.robinlovelace.net/adv-map.html [@lovelace2019geocomputation]
  * ggplot2: https://ggplot2.tidyverse.org/reference/ggsf.html [@ggplot2link]
  * ggspatial https://paleolimbot.github.io/ggspatial/ [@ggspatiallink]
  * mapview: https://r-spatial.github.io/mapview/index.html [@mapviewlink]
  * mapdeck: https://symbolixau.github.io/mapdeck/index.html [@mapdecklink]
  * leaflet: https://rstudio.github.io/leaflet/ [@leafletlink]
    
# Verwendete Pakete
Zur Visualisierung:
  
  * ggplot2 [@ggplot2]
  * ggspatial [@ggspatial]
  * grid [@R]
  * htmltools [@htmltools]
  * htmlwidgets [@htmlwidgets]
  * lattice [@lattice]
  * leaflet [@leaflet]
  * leaflet.extras [@leaflet.extras]
  * leafpop [@leafpop]
  * mapdeck [@mapdeck]
  * mapview [@mapview]
  * raster [@raster]
  * tmap [@tmap]

Für Farbpaletten:

  * RColorBrewer [@RColorBrewer]
  * scico [@scico]
  * viridis [@viridis]
  
Zum Laden und manipulieren von Daten:

  * dplyr [@dplyr]
  * plyr [@plyr]
  * readr [@readr]
  * readxl [@readxl]
  * rgdal [@rgdal]
  * rgeos [@rgeos]
  * sf [@sf]
  * stringr [@stringr]

Für Datensätze:

  * maps [@maps]
  * spData [@spData]
  * spDataLarge [@spDataLarge]

Sonstiges: 

  * magick [@magick]
    
Pakete in Verwendung mit den ShinyApps:
  * colourpicker [@colourpicker]
  * devtools [@devtools]
  * furrr [@furrr]
  * future [@future]
  * geosphere [@geosphere]
  * leafletplugins [@leafletplugins]
  * openxlsx [@xlsx]
  * osmdata [@osmdata]
  * osrm [@osrm]
  * rlist [@rlist]
  * shiny [@shiny]
  * shinydashboard [@shinydashboard]
  * shinyjs [@shinyjs]
  * shinyWidgets [@shinyWidgets]
  * sp [@sp]
  * spdep [@spdep]
  
# References
    